"""
UI tests for ROS optimizations display.

TERMINOLOGY NOTE:
- "Recommendations" = The raw suggestions generated by Kruize (the recommendation engine)
- "Optimizations" = How the UI presents these recommendations to users

The UI displays Kruize recommendations as "Optimizations" at:
  /openshift/cost-management/optimizations

These are the same data - just different terminology between backend (recommendations)
and frontend (optimizations). The ROS (Resource Optimization Service) processor
fetches recommendations from Kruize and stores them for the UI to display.

DATA REQUIREMENTS:
These tests work best when optimization data exists. To populate data:
1. Run e2e tests with E2E_CLEANUP_AFTER=false
2. Then run these UI tests

Without data, tests will verify empty state handling or skip gracefully.
"""

import re

import pytest
from playwright.sync_api import Page, expect

OPTIMIZATIONS_PATH = "/openshift/cost-management/optimizations"

TABLE_SELECTOR = "table, [role='grid'], .pf-c-table, .pf-v6-c-table"
EMPTY_STATE_SELECTOR = ".pf-c-empty-state, .pf-v6-c-empty-state, .empty-state"
CONTENT_SELECTOR = f"{TABLE_SELECTOR}, {EMPTY_STATE_SELECTOR}"

# On ephemeral CI clusters the ROS pipeline is async and the API can be slow
# to respond while data is still being processed.
CONTENT_TIMEOUT_MS = 30000


def _goto_optimizations(page: Page, ui_url: str) -> None:
    """Navigate to the optimizations page and wait for content to render."""
    page.goto(f"{ui_url}{OPTIMIZATIONS_PATH}")
    page.wait_for_load_state("networkidle")
    expect(page.locator(CONTENT_SELECTOR).first).to_be_visible(
        timeout=CONTENT_TIMEOUT_MS
    )


def _has_table(page: Page) -> bool:
    """Return True if the page contains a data table (not just empty state)."""
    return page.locator(TABLE_SELECTOR).count() > 0


# =============================================================================
# Test Classes
# =============================================================================


@pytest.mark.ui
@pytest.mark.ros
class TestOptimizationsDisplay:
    """Test the optimizations page display.
    
    These tests check the optimizations page UI. They work with or without data:
    - If data exists (from e2e tests), they verify the table displays
    - If no data, they verify the empty state displays correctly
    """

    def test_optimizations_page_loads(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify optimizations page loads and shows either data or empty state."""
        _goto_optimizations(authenticated_page, ui_url)

    def test_optimizations_table_visible_when_data_exists(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify optimizations table is displayed when data exists.
        
        This test requires data to be present (run e2e tests first with E2E_CLEANUP_AFTER=false).
        """
        _goto_optimizations(authenticated_page, ui_url)

        if not _has_table(authenticated_page):
            pytest.skip("No optimization data available - run e2e tests first with E2E_CLEANUP_AFTER=false")


@pytest.mark.ui
@pytest.mark.ros
class TestOptimizationDetails:
    """Test optimization detail views.
    
    These tests require optimization data to be present. Run e2e tests first
    with E2E_CLEANUP_AFTER=false to populate the data.
    """

    def test_can_click_optimization_row(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify clicking an optimization row navigates to details."""
        _goto_optimizations(authenticated_page, ui_url)

        optimization_link = authenticated_page.locator(
            "table tbody tr a, [role='row'] a, table tbody tr[role='row']"
        ).first

        if optimization_link.count() == 0:
            pytest.skip("No optimization rows available - run e2e tests first with E2E_CLEANUP_AFTER=false")

        optimization_link.click()
        authenticated_page.wait_for_load_state("networkidle")

        expect(authenticated_page).to_have_url(re.compile(r".*(breakdown|detail|id=).*"), timeout=10000)

    def test_optimization_page_shows_resource_info(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify optimizations page shows CPU/memory related content."""
        _goto_optimizations(authenticated_page, ui_url)

        resource_info = authenticated_page.locator(
            "text=/cpu|memory|cores|gib|container|pod|request|limit/i"
        )

        if resource_info.count() == 0:
            if authenticated_page.locator(EMPTY_STATE_SELECTOR).count() > 0:
                pytest.skip("No optimization data - run e2e tests first with E2E_CLEANUP_AFTER=false")
            pytest.skip("No resource information visible on page")

        expect(resource_info.first).to_be_visible()
