apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-onprem-database.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem-database.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "cost-onprem-database.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
