apiVersion: v2
name: cost-onprem
description: Cost Management On-Premise solution for OpenShift
type: application
version: 0.2.15
appVersion: "0.2.15"

keywords:
  - cost-management
  - resource-optimization
  - openshift
  - on-premise

maintainers:
  - name: Insights On-Premise Team

dependencies:
  - name: cost-onprem-database
    version: "0.1.0"
    repository: "file://charts/cost-onprem-database"
    condition: database.deploy
  - name: cost-onprem-cache
    version: "0.1.0"
    repository: "file://charts/cost-onprem-cache"
    condition: valkey.deploy

